name: sigesp-v2-temp
services:
  php:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: sigesp-php-v2-temp
    volumes:
      - ../src:/var/www/html
    ports:
      - "8003:80"
    depends_on:
      - postgres
    environment:
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
      - LANG=es_VE.iso885915
      - LC_ALL=es_VE.iso885915
      - LC_CTYPE=es_VE.iso885915
    env_file:
      - path: ../.env
        required: false

  postgres:
    build:
      context: .
      dockerfile: db/Dockerfile
    container_name: sigesp-postgres-v2-temp
    command: postgres -c log_statement=${POSTGRES_LOG_STATEMENT:-all}
    volumes:
      - sigesp-data-v2-1:/var/lib/postgresql/data
    ports:
      - "6003:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # Argumentos para initdb: establecer encoding LATIN9 y la locale generada en la imagen
      POSTGRES_INITDB_ARGS: "--encoding=LATIN9 --locale=es_VE.ISO-8859-15"
      # Ajustar variables de entorno para que coincidan con la locale usada por initdb
      LANG: es_VE.ISO-8859-15
      LC_ALL: es_VE.ISO-8859-15
      # TZ will be loaded from env_file
      # Path check inside Debian Stretch/Bookworm usually:
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
    env_file:
      - path: ../.env
        required: false

volumes:
  sigesp-data-v2-1:
